#!/usr/bin/env python3
"""Pre-parse the vendored HQPlayer docs into per-section files an agent can read.

``hqplayer6desktop-manual.pdf`` is 65 pages; ``pdftotext -layout`` on it is
~144 KB, which is more than any agent wants in context to answer "what does
poly-sinc-gauss-long do". Every agent that needed one paragraph was running
pdftotext itself and reading the whole dump.

This script splits that dump once, at subsection granularity, into
``docs/vendor/manual/``:

* ``manual.txt`` — the unmodified ``pdftotext -layout`` dump. Authority: if a
  split file looks wrong, this is what it was cut from.
* ``NN-MM-slug.txt`` — one file per manual subsection (``MM`` is ``00`` for a
  top-level section's own preamble). Section body text is **verbatim** from the
  layout dump, indentation and all, so the manual's tables survive as the
  column-aligned text they are. Nothing is reflowed; nothing is reformatted.
* ``INDEX.md`` — section number, title, pages, filename, so an agent can pick
  the one file it needs.
* ``readme-index.md`` — every ``Element:`` / ``Attribute:`` in
  ``hqplayerd-readme.txt`` with the line number to ``sed -n`` at. That file is
  already grep-friendly plain text, so it is indexed rather than split.

The output is derived from copyrighted Signalyst material and is gitignored,
same as its two sources. Run ``make manual`` to (re)build it.

Splitting is driven by the manual's own table of contents: the TOC is parsed
for the authoritative (number, title, page) list, then each of those headings
is located in the body **in order**. A heading the TOC promises but the body
does not contain is a hard error — a silently dropped section would leave an
agent confidently answering from a hole. The emitted files are a strict
partition of the cleaned dump, and the line counts are asserted to prove it.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / "hqplayer6desktop-manual.pdf"
README = ROOT / "hqplayerd-readme.txt"
OUT = ROOT / "docs" / "vendor" / "manual"

# TOC row: "   4.6. Filter / Oversampling selection.........................26"
TOC_ROW = re.compile(r"^\s*((?:\d+\.)+)\s*(.+?)\.{3,}\s*(\d+)\s*$")
# Page header the PDF puts at the top of every page: "        27 / 65"
PAGE_MARK = re.compile(r"^\s*(\d+)\s*/\s*\d+\s*$")
# Page footer, on every page.
FOOTER = re.compile(r"^\s*Copyright ©.*Signalyst\.\s*All rights reserved\.\s*$")
# hqplayerd-readme.txt structure: '1.1 Element "output"' / 'Attribute: type'
README_ELEMENT = re.compile(r'^\d+(?:\.\d+)*\s+Element\s+"([^"]+)"')
README_ATTRIBUTE = re.compile(r"^Attribute:\s*(\S+)")

# Prose blocks for the generated Markdown. Each of these is ONE logical line in
# the output — the repo's Markdown is soft-wrapped and a hook rejects hard wraps
# — so they are assembled here by implicit concatenation to stay inside the
# source line-length gate. Do not insert "\n".
INDEX_PROVENANCE = (
    "Generated by `scripts/build_manual.py` (`make manual`) from `hqplayer6desktop-manual.pdf`."
    " Do not edit by hand; re-run the script. This whole directory is gitignored — the manual is"
    " Signalyst's copyrighted material and neither it nor anything derived from it is redistributable."
)
INDEX_HOWTO = (
    "Read the one file you need, not the whole manual. Section bodies are verbatim `pdftotext -layout`"
    " output, so the manual's tables appear as column-aligned text rather than Markdown tables."
    " `manual.txt` is the full unsplit dump and is the authority if a section file looks wrong."
    " `[page N]` markers are kept so a finding can be cited back to a page of the PDF."
)
INDEX_ALSO = (
    "- `readme-index.md` — every config element and attribute in `hqplayerd-readme.txt`, with line"
    " numbers. That file is already plain text; read it directly with `sed -n '<line>,<line>p'`."
)
README_INDEX_PREAMBLE = (
    "Generated by `scripts/build_manual.py` (`make manual`). Line numbers are into"
    " `hqplayerd-readme.txt` at the repo root — read the block with"
    " `sed -n '<line>,+20p' hqplayerd-readme.txt`. That file is the authority for daemon config XML;"
    " this is only a table of contents for it."
)


@dataclass
class Entry:
    """One table-of-contents row."""

    number: str  # "4.6." — trailing dot included, as the manual writes it
    title: str
    page: int

    @property
    def heading(self) -> str:
        return f"{self.number} {self.title}"

    @property
    def top(self) -> int:
        return int(self.number.split(".")[0])

    @property
    def sub(self) -> int:
        parts = [p for p in self.number.split(".") if p]
        return int(parts[1]) if len(parts) > 1 else 0


@dataclass
class Unit:
    """One emitted file: a subsection, or a section's preamble."""

    entry: Entry
    lines: list[str]
    page: int
    filename: str


def norm(text: str) -> str:
    """Collapse whitespace so a body heading compares equal to its TOC row."""
    return " ".join(text.split())


def slug(title: str) -> str:
    ascii_ish = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return ascii_ish.strip("-") or "section"


def extract(pdf: Path) -> list[str]:
    """Run pdftotext -layout, or explain why we cannot."""
    if not pdf.is_file():
        sys.exit(f"missing {pdf} — the manual is gitignored; put your copy in place first")
    binary = shutil.which("pdftotext")
    if binary is None:
        sys.exit("pdftotext not found — install poppler-utils")
    try:
        # S603: the argv is this module's own literals plus a repo-relative path
        # constant, and the binary is resolved off PATH by shutil.which above.
        done = subprocess.run(  # noqa: S603
            [binary, "-layout", str(pdf), "-"],
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        sys.exit(f"pdftotext failed: {exc.stderr.strip()}")
    return done.stdout.splitlines()


def parse_toc(lines: list[str]) -> tuple[list[Entry], int]:
    """Collect TOC rows; stop at the body heading of the first entry.

    Returns the entries and the line index where the body starts.
    """
    entries: list[Entry] = []
    for index, line in enumerate(lines):
        if entries and norm(line) == entries[0].heading:
            return entries, index
        match = TOC_ROW.match(line)
        if match:
            entries.append(Entry(match.group(1), norm(match.group(2)), int(match.group(3))))
    sys.exit("could not find the body of section 1 — is this the HQPlayer manual?")


def clean(lines: list[str]) -> list[str]:
    """Drop the per-page footer, turn the page header into a citable marker.

    Runs of blank lines left behind by page breaks collapse to one. Everything
    else is passed through untouched — the manual's tables are column-aligned
    text and reflowing them would corrupt them.
    """
    out: list[str] = []
    for line in lines:
        if FOOTER.match(line):
            continue
        mark = PAGE_MARK.match(line)
        if mark:
            out.append(f"[page {mark.group(1)}]")
            continue
        if not line.strip() and out and not out[-1].strip():
            continue
        out.append(line.rstrip())
    return out


def locate(entries: list[Entry], body: list[str]) -> list[int]:
    """Index of each entry's heading in ``body``, matched in TOC order.

    Order matters: "1. This written license agreement..." in the licence text
    looks like a heading in isolation, and only the sequential scan keeps it
    from being mistaken for one.
    """
    found: list[int] = []
    cursor = 0
    for entry in entries:
        for index in range(cursor, len(body)):
            if norm(body[index]) == entry.heading:
                found.append(index)
                cursor = index + 1
                break
        else:
            sys.exit(f"section {entry.heading!r} is in the table of contents but not in the body")
    return found


def build_units(entries: list[Entry], body: list[str], starts: list[int]) -> list[Unit]:
    """Cut the body at the located headings, one Unit per emitted file."""
    bounds = [*starts, len(body)]
    units: list[Unit] = []
    for position, entry in enumerate(entries):
        lines = body[bounds[position] : bounds[position + 1]]
        name = f"{entry.top:02d}-{entry.sub:02d}-{slug(entry.title)}.txt"
        units.append(Unit(entry, lines, entry.page, name))
    return units


def write_sections(units: list[Unit]) -> int:
    """Write one file per unit; return how many body lines were written."""
    written = 0
    for unit in units:
        text = "\n".join(unit.lines).strip("\n")
        (OUT / unit.filename).write_text(text + "\n", encoding="utf-8")
        written += len(unit.lines)
    return written


# "Looking for X?" pointers for INDEX.md, as (title regex, blurb). The patterns
# are anchored on the distinctive part of a section title rather than a loose
# keyword: a bare "filter" matches §2.8 "20 kHz filter" long before it reaches
# §4.6, and "convolution" matches the §2.11 status indicator rather than the §6
# engine. If Signalyst renames a section the pointer drops out of the index,
# which is the safe failure — a pointer aimed at the wrong section is worse than
# no pointer at all.
POINTERS = [
    (r"oversampling", "PCM filter / oversampling tables (poly-sinc, sinc-M, IIR, closed-form, …)"),
    (r"^sdm$", "SDM: delta-sigma modulators, DSD rates, bit depth"),
    (r"^pcm$", "PCM: sample rates, bit depth, dither"),
    (r"^matrix processing$", "Matrix processing: channel routing and per-channel plugins"),
    (r"^convolution engine$", "Convolution engine: impulse responses, filter files"),
    (r"^advanced$", "Advanced tab: buffers, CUDA/offload, metering"),
    (r"^troubleshooting$", "Troubleshooting: no rates available, USB problems"),
]


def pointers(entries: list[Entry]) -> list[str]:
    """ "Looking for X?" lines, derived from TOC titles so they cannot go stale."""
    out: list[str] = []
    for pattern, blurb in POINTERS:
        hit = next((e for e in entries if re.search(pattern, e.title.lower())), None)
        if hit:
            out.append(f"- **{blurb}** — §{hit.number.rstrip('.')} {hit.title}")
    return out


def write_index(units: list[Unit], entries: list[Entry]) -> None:
    rows = [
        "| Section | Title | Page | File |",
        "| --- | --- | --- | --- |",
    ]
    for unit in units:
        number = unit.entry.number.rstrip(".")
        rows.append(f"| {number} | {unit.entry.title} | {unit.page} | `{unit.filename}` |")

    body = [
        "# HQPlayer Desktop manual — agent index",
        "",
        INDEX_PROVENANCE,
        "",
        INDEX_HOWTO,
        "",
        "## Looking for",
        "",
        *pointers(entries),
        "",
        "## Sections",
        "",
        *rows,
        "",
        "## Also here",
        "",
        INDEX_ALSO,
        "",
    ]
    (OUT / "INDEX.md").write_text("\n".join(body) + "\n", encoding="utf-8")


def write_readme_index(readme: Path) -> int:
    """Index hqplayerd-readme.txt's element/attribute blocks. Returns the count."""
    if not readme.is_file():
        print(f"skipping readme index: {readme} not present")
        return 0
    rows = ["| Element | Attribute | Line |", "| --- | --- | --- |"]
    element = "—"
    count = 0
    for number, line in enumerate(readme.read_text(encoding="utf-8").splitlines(), start=1):
        found = README_ELEMENT.match(line)
        if found:
            element = found.group(1)
            rows.append(f"| `{element}` | *(element)* | {number} |")
            count += 1
            continue
        attribute = README_ATTRIBUTE.match(line)
        if attribute:
            rows.append(f"| `{element}` | `{attribute.group(1)}` | {number} |")
            count += 1
    body = [
        "# hqplayerd-readme.txt — config element/attribute index",
        "",
        README_INDEX_PREAMBLE,
        "",
        *rows,
        "",
    ]
    (OUT / "readme-index.md").write_text("\n".join(body) + "\n", encoding="utf-8")
    return count


def main() -> None:
    raw = extract(PDF)
    entries, body_start = parse_toc(raw)
    body = clean(raw[body_start:])
    units = build_units(entries, body, locate(entries, body))

    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("*.txt"):
        stale.unlink()
    (OUT / "manual.txt").write_text("\n".join(raw) + "\n", encoding="utf-8")

    written = write_sections(units)
    if written != len(body):
        sys.exit(f"split lost lines: emitted {written} of {len(body)} — output is not a partition")
    write_index(units, entries)
    indexed = write_readme_index(README)

    print(f"{OUT.relative_to(ROOT)}: {len(units)} sections, {len(body)} lines, {indexed} config attributes")


if __name__ == "__main__":
    main()
